#! /bin/sh

$HOME/.scripts/sxhkd.sh &
$HOME/.scripts/polyb.sh &
xsetroot -cursor_name left_ptr &

xautolock -corners ---- -cornersize 5 -time 10 -locker "betterlockscreen -l blur >> /dev/null" &

bspc monitor HDMI-0 -d I II III IV V VI VII VIII IX X
bspc monitor DVI-I-0 -d XI XII XIII XIV
bspc monitor ^1 -s ^2

bspc config border_width            2
# unfocused window
bspc config normal_border_color     \#000000
# focused window of focused monitor
bspc config focused_border_color    \#5543f5
# focused window of unfocused monitor
bspc config active_border_color     \#ae43f5
bspc config window_gap              5
bspc config bottom_padding          0
#bspc config top_padding             0

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config single_monocle          true    # for smart gaps

bspc config focus_follows_pointer   true

#bspc rule -a Firefox desktop='^2'
bspc rule -a Zathura state=tiled
